<a href="https://colab.research.google.com/github/anhtin18/SGU26_Ml/blob/main/chuong7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, Normalizer, Binarizer
from numpy import set_printoptions

array = data.values
X = array[:,0:8]
Y = array[:,8]

# 1. Rescale Data (Đưa về 0-1)
scaler = MinMaxScaler(feature_range=(0, 1))
rescaledX = scaler.fit_transform(X)
set_printoptions(precision=3)
print("Rescaled (Dòng đầu):\n", rescaledX[0:5,:])

# 2. Standardize Data (Mean=0, StdDev=1)
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)
print("Standardized (Dòng đầu):\n", rescaledX[0:5,:])

# 3. Normalize Data (Độ dài vector = 1)
scaler = Normalizer().fit(X)
normalizedX = scaler.transform(X)
print("Normalized (Dòng đầu):\n", normalizedX[0:5,:])

# 4. Binarize Data (Theo ngưỡng)
binarizer = Binarizer(threshold=0.0).fit(X)
binaryX = binarizer.transform(X)
print("Binarized (Dòng đầu):\n", binaryX[0:5,:])


Rescaled (Dòng đầu):
 [[0.556 0.    0.    0.    0.    0.    0.    0.   ]
 [0.778 0.    0.    0.    0.    0.    0.    0.   ]
 [1.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.556 0.    0.    0.    0.    0.    0.    0.   ]
 [0.222 0.    0.    0.    0.    0.    0.    0.   ]]
Standardized (Dòng đầu):
 [[ 0.183  0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.875  0.     0.     0.     0.     0.     0.     0.   ]
 [ 1.566  0.     0.     0.     0.     0.     0.     0.   ]
 [ 0.183  0.     0.     0.     0.     0.     0.     0.   ]
 [-0.854  0.     0.     0.     0.     0.     0.     0.   ]]
Normalized (Dòng đầu):
 [[1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]]
Binarized (Dòng đầu):
 [[1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
